language: go
go:
    - 1.6
    - 1.6.1
    - 1.6.2
    - tip
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - go get -u github.com/mattn/goveralls
    - go get -u golang.org/x/tools/cmd/cover
install:
    - go get -u github.com/teh-cmc/seq/... || true
script:
    - SEQ_SERVERS=5 SEQ_FSYNC=1 go test -v -cpu 1,4,8 -run=. -bench=none -covermode=count -coverprofile=coverage.out $(go list github.com/teh-cmc/seq/rr_seq | grep -v /vendor/)
    - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

